#!/bin/bash

source ./.config

source ${DIR_INC}/log

function	test::log()
{
	local	old_log_pad_str="${LOG_PAD_STR}"

	# all default
	log::print "no_format" "THIS IS A LOGGED AND PRINTED TEXT"
	# no format (DEFAULT)
	log::print "THIS IS A LOGGED AND PRINTED TEXT" -1
	# failed
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 0
	# success
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 1
	# info
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 2
	# warn
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 3

	# padding 0 (DEFAULT)
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 1 0
	# padding 1
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 1 1
	# changing LOG_PAD_STR
	LOG_PAD_STR="[+]"
	log::print "THIS IS A LOGGED AND PRINTED TEXT" 1 2
	LOG_PAD_STR="${old_log_pad_str}"

	# both (DEFAULT)
	log::print "THIS IS A LOGGED AND PRINTED TEXT" -1 0 3
	# only file
	log::print "THIS IS A LOGGED TEXT" -1 0 2
	# only stdout
	log::print "THIS IS A PRINTED TEXT" -1 0 1



	# all default
	log::main_title "THIS IS A TITLE"
	# both (DEFAULT)
	log::main_title "THIS IS A TITLE" 3
	# log file only
	log::main_title "THIS IS A TITLE" 2
	# stdout only
	log::main_title "THIS IS A TITLE" 1
	# Specify color
	log::main_title "THIS IS A TITLE" 1 "${ORA}"

	# print main_title with colors in title
	## have to toggle ANSI enclosing one by pass one to ansi::toggle
	ansi::toggle 1
	log::main_title "${RED}BIG${RST} ${BLU}TITLE${RST}" 3
	## disable ANSI enclosing
	ansi::toggle
}

test::log
