#!/bin/bash

source ./.config

source "${DIR_INC}/part/log"

function	test::log()
{
	local	old_log_pad_str="${LOG_PAD_STR}"

	# all default
	log::print "THIS IS A LOGGED AND PRINTED TEXT"
	# no format (DEFAULT)
	log::print "THIS IS A LOGGED AND PRINTED TEXT" raw
	# failed
	log::print "THIS IS A LOGGED AND PRINTED TEXT" fail
	# success
	log::print "THIS IS A LOGGED AND PRINTED TEXT" pass
	# info
	log::print "THIS IS A LOGGED AND PRINTED TEXT" info
	# ques
	log::print "THIS IS A LOGGED AND PRINTED TEXT" ques
	# warn
	log::print "THIS IS A LOGGED AND PRINTED TEXT" warn

	# padding 0 (DEFAULT)
	log::print "THIS IS A LOGGED AND PRINTED TEXT" fail 0
	# padding 1
	log::print "THIS IS A LOGGED AND PRINTED TEXT" fail 1
	# changing LOG_PAD_STR
	LOG_PAD_STR="[+]"
	log::print "THIS IS A LOGGED AND PRINTED TEXT" fail  2
	LOG_PAD_STR="${old_log_pad_str}"

	# both (DEFAULT)
	log::print "THIS IS A LOGGED AND PRINTED TEXT" raw 0 3
	# only file
	log::print "THIS IS A LOGGED TEXT" raw 0 2
	# only stdout
	log::print "THIS IS A PRINTED TEXT" raw 0 1



	# all default
	log::main_title "THIS IS A TITLE"
	# both (DEFAULT)
	log::main_title "THIS IS A TITLE" 3
	# log file only
	log::main_title "THIS IS A TITLE" 2
	# stdout only
	log::main_title "THIS IS A TITLE" 1
	# Specify color
	log::main_title "THIS IS A TITLE" 1 "${ORA}"

	log::main_title "${RED}BIG${RST} ${BLU}TITLE${RST}" 3
}

test::log
