#!/bin/bash

source ./.config

function	test::print()
{
	local	msg="${1:-}"

	print::info "${msg}"
	print::warn "${msg}"
	print::ques "${msg}"
	print::pass "${msg}"
	print::pass "${msg}" 0
	print::erro "${msg}"
	print::err::usage "${msg}"
	print::err::no_such_file "${msg}"
	print::pause
}

test::print "${@}"
