#!/bin/bash

source ./.config

function	test::print()
{
	local	msg="${1:-}"

	print::info "${msg}"
	print::warn "${msg}"
	print::ques "${msg}"
	print::pass "${msg}"
	print::pass "${msg}" 0
	print::erro "${msg}"
	print::erro_parse "${msg}"
	print::errno_2 "${msg}"
	print::pause
}

test::print "${@}"
