#!/bin/bash

source ./.config

function	test::progress_bar()
{
	choices=(
		"first"
		"second"
		"third"
		"fourth"
		"fifth"
		"sixth"
		"seventh"
		"eigth"
		"nineth"
		"tenth"
		"elventh"
		"tweleveth"
		"thirteenth"
		"jskladnfkjsdnfkjsdnffirst"
		"jskladnfkjsdnfkjsdnfsecond"
		"jskladnfkjsdnfkjsdnfthird"
		"jskladnfkjsdnfkjsdnffourth"
		"jskladnfkjsdnfkjsdnffifth"
		"jskladnfkjsdnfkjsdnfsixth"
		"jskladnfkjsdnfkjsdnfseventh"
		"jskladnfkjsdnfkjsdnfeigth"
		"jskladnfkjsdnfkjsdnfnineth"
		"jskladnfkjsdnfkjsdnftenth"
		"jskladnfkjsdnfkjsdnfelventh"
		"jskladnfkjsdnfkjsdnftweleveth"
		"jskladnfkjsdnfkjsdnfthirteenth"
	)

	pb::init "${choices[@]}"

	for item in "${choices[@]}"; do
		pb::print "${item}"
		sleep 0.1
	done
	pb::done "Test"
}

test::progress_bar
