#!/bin/bash

## install lib_bash
DIR_LIB="${HOME}/.local/lib"
DIR_LIB_BASH="${DIR_LIB}/lib_bash"
[ ! -d "${DIR_LIB}" ] && mkdir -p "${DIR_LIB}"
if [ ! -d "${DIR_LIB_BASH}" ]; then
	echo "lib bash is not installed installing it."
	git clone https://github.com/Pixailz/lib_bash "${DIR_LIB_BASH}"
else
	echo "lib bash is installed"
	. "${DIR_LIB_BASH}/.config"
	base::update
fi
