#!/bin/bash

## ⚠️ TEST ZONE ⚠️
LOAD_DL="\xe2\x96\x96"	# ▖
LOAD_DR="\xe2\x96\x97"	# ▗
LOAD_UL="\xe2\x96\x98"	# ▘
LOAD_UR="\xe2\x96\x9d"	# ▝

# LOAD_DL="\xe2\x96\x9c"	# ▜
# LOAD_DR="\xe2\x96\x9b"	# ▛
# LOAD_UL="\xe2\x96\x9f"	# ▟
# LOAD_UR="\xe2\x96\x99"	# ▙

function	load::load_dot()
{
	local	title="${1}"
	local	curr_char="${LOAD_DL}"

	printf "\x0a"
	while true; do
		ansi::move_up_del_print " ${curr_char} ${title}\n"
		case "${curr_char}" in
			"${LOAD_DL}") curr_char="${LOAD_DR}";;
			"${LOAD_DR}") curr_char="${LOAD_UR}";;
			"${LOAD_UR}") curr_char="${LOAD_UL}";;
			"${LOAD_UL}") curr_char="${LOAD_DL}";;
		esac
		sleep 0.2
	done
}

## ⚠️ END TEST ZONE ⚠️

source ./.config

parse::entry ${@}
