#!/bin/bash

: "
${DIR_INC}/part/adb
	adb include file, those include:
		- ${DIR_SRC}/android/adb
depend on:
		- ${DIR_INC}/base
"

[ "${INC_PROT_ADB:-0}" == 1 ] && return || INC_PROT_ADB=1

# DEPENDENCIES
source ${DIR_INC}/base

source ${DIR_SRC}/android/adb
