#!/bin/bash

: "
${DIR_INC}/part/ansi
	ansi include file, those include:
		- ${DIR_SRC}/ansi
depend on:
		- ${DIR_INC}/part/print
"

[ "${INC_PROT_ANSI:-0}" == 1 ] && return || INC_PROT_ANSI=1

# DEPENDENCIES
source "${DIR_INC}/part/print"

# ANSI CHAR CONFIG
## BASE
NO_ANSI=0
ESC="\e"
BEG_ANSI="\x01"
END_ANSI="\x02"

LOAD_TTS=0.2
DOWN_TTS=0.2

## set enclosed ansi char, help to count printable character displayed, for
## centered text for exemple
USE_ENCL_ANSI=1

declare -gA ANSI
ANSI=(
		# COLOR
	["RST"]="[00m"			# RESET
	["WHI"]="[38;5;15m"		# WHITE
	["GRA"]="[38;5;242m"	# GRAY
	["BLA"]="[38;5;16m"		# BLACK

	["GRE"]="[38;5;40m"		# GREEN
	["RED"]="[38;5;196m"	# RED
	["BLU"]="[34m"			# BLUE
	["YEL"]="[33m"			# YELLOW
	["CYA"]="[36m"			# CYAN
	["MAG"]="[35m"			# MAGENTA
	["PUR"]="[38;5;93m"		# PURPLE
	["PIN"]="[38;5;207m"	# PINK
	["ORA"]="[38;5;208m"	# ORANGE

	["LGRE"]="[92m"			# LIGHT GREEN
	["LYEL"]="[93m"			# LIGHT_YELLOW
	["LBLU"]="[94m"			# LIGHT_BLUE
	["LMAG"]="[95m"			# LIGHT_MAGENTA
	["LCYA"]="[96m"			# LIGHT_CYAN
		# MODIFIER
	["BLI"]="[05m"			# BLINKING
	["BOL"]="[01m"			# BOLD
		# CURSOR THING
	["ENA_CUR"]="[?25h"
	["DIS_CUR"]="[?25l"
	["DEL_LIN"]="[2K"
	["MOV_1UP"]="[1F"
	["CLR_SCR"]="[2J"
	["CUR_HOME"]="[H"
	["POS_REQ"]="[6n"
)

## UNICODE CHAR

### Box char
BOX_HO="═"
BOX_VE="║"
BOX_UL="╔"
BOX_UR="╗"
BOX_LL="╚"
BOX_LR="╝"

# BRAILLE CHAR
# https://www.compart.com/fr/unicode/block/U+2800

DOWN_80="⣿"
DOWN_70="⣷"
DOWN_71="⣾"
DOWN_60="⣶"
DOWN_50="⣦"
DOWN_51="⣴"
DOWN_40="⣤"
DOWN_30="⣄"
DOWN_31="⣠"
DOWN_20="⣀"
DOWN_10="⡀"
DOWN_11="⢀"
DOWN_00="⠀"

LOAD_7="⡿"
LOAD_6="⣟"
LOAD_5="⣯"
LOAD_4="⣷"
LOAD_3="⣾"
LOAD_2="⣽"
LOAD_1="⣻"
LOAD_0="⢿"

PG_SPLIT="╸"
PG_FULL="━"

declare -gA FONT_CHAR
FONT_CHAR=(
	["LOGO_DOCKER"]="󰡨"
	["LOGO_UBUNTU"]=""
	["LOGO_DEBIAN"]=""
	["LOGO_TERMUX"]=""
	["LOGO_KALI"]=""
	["LOGO_ALPINE"]=""
	["LOGO_ARCH"]="󰣇"
	["LOGO_SSH"]=""
	["LOGO_APPLE"]=""
	["LOGO_GIT"]=""
	["LOGO_WSL"]="󰨡"
)

# if not monospaced font, pad the icon with a space
[ "${HAVE_MONO_FONT:-1}" == "1" ] && UNI_PAD="" || UNI_PAD=" "

for key in ${!FONT_CHAR[@]}; do
	declare -g "${key}"="${FONT_CHAR[${key}]}${UNI_PAD}"
done

source "${DIR_SRC}/base/ansi"
