#!/bin/bash

: "
${DIR_INC}/part/ansi
	ansi include file, those include:
		- ${DIR_SRC}/ansi
depend on:
		- ${DIR_INC}/part/print
"

[ "${INC_PROT_ANSI:-0}" == 1 ] && return || INC_PROT_ANSI=1

# DEPENDENCIES
source ${DIR_INC}/part/print

# ANSI CHAR CONFIG
## BASE
NO_ANSI=0
DEFAULT_ANSI_ESC="\x1b["
BEG_ANSI="\001"
END_ANSI="\002"

LOAD_TTS=0.2
DOWN_TTS=0.2

## set enclosed ansi char, help to count printable character displayed, for
## centered text for exemple
USE_ENCL_ANSI=1

declare -gA ANSI
ANSI=(
		# COLOR
	["RST"]="0m"		# RESET
	["G"]="38;5;40m"	# GREEN
	["R"]="38;5;196m"	# RED
	["B"]="34m"			# BLUE
	["Y"]="33m"			# YELLOW
	["C"]="36m"			# CYAN
	["M"]="35m"			# MAGENTA
	["O"]="38;5;214m"	# ORANGE
	["LG"]="92m"		# LIGHT GREEN
	["LY"]="93m"		# LIGHT_YELLOW
	["LB"]="94m"		# LIGHT_BLUE
	["LM"]="95m"		# LIGHT_MAGENTA
	["LC"]="96m"		# LIGHT_CYAN
		# MODIFIER
	["BL"]="05m"		# BLINKING
		# CURSOR THING
	["ENA_CUR"]="?25h"
	["DIS_CUR"]="?25l"
	["DEL_LIN"]="2K"
	["MOV_1UP"]="1F"
	["CLR_SCR"]="2J"
	["CUR_HOME"]="H"
)

## UNICODE CHAR

### Box char
BOX_HO="═"
BOX_VE="║"
BOX_UL="╔"
BOX_UR="╗"
BOX_LL="╚"
BOX_LR="╝"

# BRAILLE CHAR
# https://www.compart.com/fr/unicode/block/U+2800

DOWN_80="⣿"
DOWN_70="⣷"
DOWN_71="⣾"
DOWN_60="⣶"
DOWN_50="⣦"
DOWN_51="⣴"
DOWN_40="⣤"
DOWN_30="⣄"
DOWN_31="⣠"
DOWN_20="⣀"
DOWN_10="⡀"
DOWN_11="⢀"
DOWN_00="⠀"

LOAD_7="⡿"
LOAD_6="⣟"
LOAD_5="⣯"
LOAD_4="⣷"
LOAD_3="⣾"
LOAD_2="⣽"
LOAD_1="⣻"
LOAD_0="⢿"

PG_SPLIT="╸"
PG_FULL="━"

source ${DIR_SRC}/base/ansi
