#!/bin/bash

: "
${DIR_INC}/part/cli
	cli include file, those include:
		- ${DIR_SRC}/cli
depend on:
		- ${DIR_INC}/base/utils
"

[ "${INC_PROT_CLI:-0}" == 1 ] && return || INC_PROT_CLI=1

# DEPENDENCIES
source "${DIR_INC}/part/utils"

# check on which os we are
if [ $(type -t termux-setup-storage) ]; then
	OS_ID="termux"
else
	if [ -f /etc/os-release ]; then
		# ubuntu
		# debian
		# alpine
		# arch
		# manjaro
		# linuxmint
		# elementary
		# rocky
		# opensuse-leap
		# fedora
		# centos
		# rhel
		# gentoo
		# kali
		# parrot
		# amzn
		# ol (oracle linux)
		# photon
		# clear-linux-os
		OS_ID=$(. /etc/os-release && printf "${ID}")
		if [ -z "${OS_ID}" ]; then
			case "$(. /etc/os-release && echo "${NAME}")" in
				"BlackArch")			OS_ID=blackarch	;;
			esac
		fi
	else
		OS_ID=Unknown
	fi
fi

IS_WSL_INSTANCE="$(grep -i "Microsoft" /proc/version 2>&1 >/dev/null || true)"

export IS_WSL_INSTANCE
export OS_ID

source "${DIR_SRC}/base/cli"
