#!/bin/bash

: "
${DIR_INC}/part/template
	log include file, those include:
		- ${DIR_SRC}/log/utils
depend on:
		- ${DIR_INC}/base
"

[ "${INC_PROT_PARSE:-0}" == 1 ] && return || INC_PROT_PARSE=1

# DEPENDENCIES
source ${DIR_INC}/base

# CONFIG
PARSE_OPT_SHORT="vh"
PARSE_OPT_LONG="help,version,vv,vvv,no-color,required-opt:,optional-opt::"

PARSE_COL_LONG=15
PARSE_COL_DESC=31
PARSE_COL_LAST_SEC=20

PARSE_FUNC_HELP="parse::usage"
PARSE_FUNC_VERSION="parse::print_infos"
PARSE_FUNC_INVALID_OPT="parse::invalid"

source ${DIR_SRC}/parse
