#!/bin/bash

: "
${DIR_INC}/part/progress_bar
	pb:: include file, those include:
		- ${DIR_SRC}/progress_bar
depend on:
		- ${DIR_INC}/base
"

[ "${INC_PROT_PROGRESS_BAR:-0}" == 1 ] && return || INC_PROT_PROGRESS_BAR=1

# DEPENDENCIES
source "${DIR_INC}/base"

# ANSI CHAR CONFIG
PB_LEN=40
PB_FULL="█"
PB_HEAD="▒"
PB_EMPTY=" "

PB_BEGIN_TS=""
PB_LENGTH=""
PB_INDEX=""

source "${DIR_SRC}/progress_bar"
