#!/bin/bash

: "
${DIR_INC}/part/tui
	tui include file, those include:
		- ${DIR_SRC}/tui
depend on:
		- ${DIR_INC}/base
"

[ "${INC_PROT_TUI:-0}" == 1 ] && return || INC_PROT_TUI=1

# DEPENDENCIES
source ${DIR_INC}/base

declare -A WAIT_LIST=()

source ${DIR_SRC}/tui
