#!/bin/bash

: "
${DIR_INC}/part/*
	Include all lib, those include:
		- ${DIR_INC}/part/base
		- ${DIR_INC}/part/progress_bar
		- ${DIR_INC}/part/android
		- ${DIR_INC}/part/log
		- ${DIR_INC}/part/tui
		- ${DIR_INC}/part/android
		- ${DIR_INC}/part/progess_bar
		- ${DIR_INC}/part/parse
"

# BASE PART
source "${DIR_INC}/base"
# ANDROID PART
source "${DIR_INC}/android"

# ORTHER
source "${DIR_INC}/part/log"
source "${DIR_INC}/part/tui"
source "${DIR_INC}/part/progress_bar"
source "${DIR_INC}/part/parse"
