#!/bin/bash

: "
${DIR_INC}/android
	android include file, those include:
		- ${DIR_SRC}/android/adb
		- ${DIR_SRC}/android/twrp
depend on:
		- ${DIR_INC}/base
"

[ "${INC_PROT_ANDROID:-0}" == 1 ] && return || INC_PROT_ANDROID=1

# DEPENDENCIES
source ${DIR_INC}/base

DIR_ANDROID="${DIR_SRC}/android"
PT_DIR="${DIR_ANDROID}/file/platform-tools"
ADB="${PT_DIR}/adb"
FASTBOOT="${PT_DIR}/fastboot"

DFLT_TWRP_BOOT="${DIR_ANDROID}/file/twrp-3.7.0_9-0-fajita.img"
DFLT_TWRP_INST="${DIR_ANDROID}/file/twrp-installer-3.7.0_9-0-fajita.zip"

TTS_ADB=1

source ${DIR_SRC}/android/adb
source ${DIR_SRC}/android/twrp


