#!/bin/bash

DIR_LIB_BASE="${DIR_SRC}/base"

: "
${DIR_LIB_BASE}/
	Base include file, those include:
		- ${DIR_LIB_BASE}/ansi
		- ${DIR_LIB_BASE}/print
		- ${DIR_LIB_BASE}/log
		- ${DIR_LIB_BASE}/utils
		- ${DIR_LIB_BASE}/progress_bar
		- ${DIR_LIB_BASE}/parse
"

[ "${INC_PROT_BASE:-0}" == 1 ] && return

source ${DIR_LIB_BASE}/ansi
source ${DIR_LIB_BASE}/print
source ${DIR_LIB_BASE}/log
source ${DIR_LIB_BASE}/utils
source ${DIR_LIB_BASE}/progress_bar
source ${DIR_LIB_BASE}/parse

INC_PROT_BASE=1
