#!/bin/bash

: "
${DIR_INC}/log
	log include file, those include:
		- ${DIR_SRC}/log
depend on ${DIR_INC}/base
"

# DEPENDENCIES
source ${DIR_INC}/base

[ "${INC_PROT_LOG:-0}" == 1 ] && return

source ${DIR_SRC}/log

INC_PROT_LOG=1
