#!/bin/bash

: "
${DIR_INC}/progress_bar
	log include file, those include:
		- ${DIR_SRC}/progress_bar/utils
depend on ${DIR_INC}/base
"

source ${DIR_INC}/base

[ "${INC_PROT_PROGRESS_BAR:-0}" == 1 ] && return

source ${DIR_SRC}/progress_bar

INC_PROT_PROGRESS_BAR=1
