#!/bin/bash

TRAP_ARG_EXIT="${TRAP_ARG_EXIT:-false}"
TRAP_ARG_DEBUG="${TRAP_ARG_DEBUG:-false}"
TRAP_ARG_RETURN="${TRAP_ARG_RETURN:-false}"
TRAP_ARG_ERROR="${TRAP_ARG_ERROR:-false}"

function	trap::enable()
{
	: "
	INFO
		LIB				template
		FUNCTION		pass
		DESC			print pass or fail according to MODE, then print MSG
		ARG				[1] MSG=${1}
						[2] MODE=${2:-1}
							> maybe 0 to fail or 1 to pass, default to 1
		RETURN_VALUE	STATUS
							> if failed set STATUS to FAILED
	"
	local	func="${1}"
	local	func="${2:None}"

	[ "${TRAP_ARG_EXIT}" ] && trap exit(0)
	[ "${TRAP_ARG_DEBUG}" ] && trap
	[ "${TRAP_ARG_RETURN}" ] && trap
	[ "${TRAP_ARG_ERROR}" ] && trap
}
