#!/bin/bash

function	print::info()
{
	: "
	INFO
		LIB				print
		FUNCTION		info
		DESC			Print some information
	"
	printf "%b %b%b\n" "${P_INFO}" "${1:-}" "${RST}"
}

function	print::warn()
{
	: "
	INFO
		LIB				print
		FUNCTION		warn
		DESC			Print a warning message
	"
	printf "%b %b%b\n" "${P_WARN}" "${1:-}" "${RST}"
}

function	print::ques()
{
	: "
	INFO
		LIB				print
		FUNCTION		ques
		DESC			Print question message
	"
	printf "%b %b%b\n" "${P_QUES}" "${1:-}" "${RST}"
}

function	print::pass()
{
	: "
	INFO
		LIB				print
		FUNCTION		pass
		DESC			Print pass or failed message, default to pass
		ARG				[1] msg=${1:-}
						[2] have_pass=${2:-1}
	"
	local	msg="${1:-}"
	local	have_pass="${2:-1}"
	local	suffix

	[ ${have_pass} == 0 ] && suffix=${P_FAIL} || suffix=${P_PASS}
	printf "%b %b%b\n" ${suffix} "${msg}" ${RST}
}

function	print::erro()
{
	: "
	INFO
		LIB				print
		FUNCTION		erro
		DESC			Print error and quit
		ARG				[1] msg=${1:-}
	"
	local	msg=${1:-}

	printf "%b %b%b\n" "${P_ERRO}" "${msg}" "${RST}"
}

function	print::err::usage()
{
	: "
	INFO
		LIB				print
		FUNCTION		err::usage
		DESC			print usage
		ARG				SCRIPT_NAME=${SCRIPT_NAME}
						[1] msg=${1:-}
	"
	local	msg="${1:-}"

	printf "%s : %b\n" "${SCRIPT_NAME}" "${msg}"
	printf "Try '%s --help' for more information.\n" "${SCRIPT_NAME}"
}

function	print::err::no_such_file()
{
	: "
	INFO
		LIB				print
		FUNCTION		err::no_such_file
		DESC			Error message for not founding a file
		ARG				[1] file_path=${1}
	"
	local	file_path="${1:-}"

	print::warn "No such file or directory (${O}${1}${RST})."
}

function	print::pause()
{
	: "
	INFO
		LIB				print
		FUNCTION		pause
		DESC			Print pause message and wait
	"
	print::info "Press [Enter] to continue.."
	read readEnterkey
}
